name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Clean Install
      run: |
        rm -rf node_modules package-lock.json
        npm install

    - name: Install Jest Globally (fix)
      run: npm install -g jest

    - name: Run Tests
      run: jest